version: "3"
x-directus: &directus
  image: linefusion/directus:latest
  volumes:
    - vol-extensions:/directus/extensions
    - vol-database:/directus/database
    - vol-uploads:/directus/uploads
    - vol-packages:/directus/packages
    - vol-node_modules:/directus/node_modules
  environment:
    DIRECTUS_VERSION: "10.5.3"
    NODE_PACKAGES: |
      directus-extension-blurhash
      directus-extension-thumbhash
      @linefusion/directus-extension-text-extractor
    DIRECTUS_BOOTSTRAP_ENABLED: "false"
    ADMIN_EMAIL: "admin@example.com"
    ADMIN_PASSWORD: "linefusion"

services:
  directus-install:
    <<: *directus
    command: directus install

  directus-bootstrap:
    <<: *directus
    command: directus bootstrap
    depends_on:
      directus-install:
        condition: service_completed_successfully

  directus:
    <<: *directus
    command: directus start
    ports:
      - "8055:8055"
    depends_on:
      directus-bootstrap:
        condition: service_completed_successfully

volumes:
  vol-extensions:
  vol-database:
  vol-uploads:
  vol-packages:
  vol-node_modules:
