version: "3"
services:
  directus:
    image: linefusion/directus:latest
    environment:
      DIRECTUS_VERSION: "10.5.3"
      NODE_PACKAGES: |
        directus-extension-blurhash
        directus-extension-thumbhash
        @linefusion/directus-extension-text-extractor
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "linefusion"
    ports:
      - "8055:8055"
    volumes:
      - extensions-volume:/directus/extensions
      - database-volume:/directus/database
      - uploads-volume:/directus/uploads

      # Extras (optional, recommended)
      # Mounting these will speed up the startup process.
      # DO NOT mount them as a bind mount (e.g. ./node_modules:/directus/node_modules).
      # Let the container runtime manage the volume instead.
      - packages-volume:/directus/packages
      - modules-volume:/directus/node_modules

volumes:
  extensions-volume:
  database-volume:
  uploads-volume:

  # Extras (optional, recommended)
  packages-volume:
  modules-volume:
