on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Enable PNPM
        run: corepack enable pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Fetch versions
        run: pnpm run build:version
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: Directs updates
